# .github/workflows/main.yml
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Stats
        run: |
          curl -s -o github-stats.svg  "https://github-readme-stats.vercel.app/api?username=Amir-rfz&show_icons=true&locale=en&count_private=true&cache_seconds=3600"
          curl -s -o github-streak.svg "https://github-readme-streak-stats.herokuapp.com/?user=Amir-rfz&count_private=true&cache_seconds=3600"
          curl -s -o github-langs.svg  "https://github-readme-stats.vercel.app/api/top-langs?username=Amir-rfz&layout=compact&langs_count=10&count_private=true&cache_seconds=3600"

      - name: Update README
        run: |
          sed -i '/github-stats.svg/c\<img src="github-stats.svg" />' README.md
          sed -i '/github-streak.svg/c\<img src="github-streak.svg" />' README.md
          sed -i '/github-langs.svg/c\<img src="github-langs.svg" />' README.md

      - name: Commit and Push Changes
        run: |
          git config --local user.name  "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .                                     # ← stage README + SVGs
          git commit -m "Update GitHub Stats" --allow-empty
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
