name: Generate Pac‑Man contribution graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"    # at 00:00 & 12:00 UTC daily
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate Pac‑Man SVGs
        uses: abozanona/pacman-contribution-graph@1.0.10.2
        with:
          github_user_name: ${{ github.repository_owner }}
          # github_token defaults to ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to `output` branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
