name: Generate Pac‑Man contribution graph

on:
  schedule:
    # run once at 00:00 and once at 12:00 UTC every day
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate pacman-contribution-graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          output: svg       # ← make sure you request SVG!

      - name: Publish to `output` branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist  # ← the action will create `dist/*.svg`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
